### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getClassList' of null

### ISSUE THREAD

**Issue by tikaPahadi** [Gert-dev/php-integrator-autocomplete-plus#23] opened 2015-11-28 06:17 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [php-integrator-autocomplete-plus](https://github.com/Gert-dev/php-integrator-autocomplete-plus) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getClassList' of null

```
At /Users/tika/.atom/packages/php-integrator-autocomplete-plus/lib/ClassProvider.coffee:38

TypeError: Cannot read property 'getClassList' of null
    at ClassProvider.module.exports.ClassProvider.getSuggestions (/Users/tika/.atom/packages/php-integrator-autocomplete-plus/lib/ClassProvider.coffee:38:24)
    at /Users/tika/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Users/tika/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Users/tika/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Users/tika/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /Users/tika/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
 16x -3:48.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:44 core:save (atom-text-editor.editor.is-focused)
     -3:08.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:04.4.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -3:04.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:03.2.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -3:03.1.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.mini.is-focused)
     -2:58.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  6x -2:58.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:20 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:16.8.0 core:undo (atom-text-editor.editor.mini.is-focused)
     -2:13.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -1:11.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:54.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:51.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.1.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.1
autocomplete-php, v0.3.7
color-picker, v2.0.13
php-integrator-autocomplete-plus, v0.3.0

# Dev
No dev packages
```

**Comment by Gert-dev** [comment] 2015-11-28 09:43
Thanks for your report, but a duplicate of #18.

**Closed by Gert-dev** 2015-11-28 09:43 UTC
