### ISSUE TITLE
Stubs.php file / code analysis

### ISSUE THREAD

**Issue by pwFoo** [Gert-dev/php-integrator-autocomplete-plus#8] opened 2015-11-08 19:16 UTC
Hi,

will php-integrator-autocomplete-plus will stubs.php usage possible with atom editor?

I searching for a solution to autocomplete framework classes and attributes provided by an stubs file.

**Comment by Gert-dev** [comment] 2015-11-08 19:37
Hello, are you looking for a way to include a single file containing global functions, constants and classes that are available in the rest of your codebase without a use statement or namespacing? If that is the case, then yes! As indicated in the changelog of the [base package](https://github.com/Gert-dev/php-integrator-base/blob/master/CHANGELOG.md), starting with version 0.2.0 you will be able to add these sorts of files in the settings screen.

**Comment by pwFoo** [comment] 2015-11-08 20:17
Hi @Gert-dev 
the used php framework will use namespaces in the next version, but I don't know much about namespaces in PHP at the moment.
Current version has a stubs.php generator which provides an generated stubs.php file with all the classes, attributes, ...

So it sounds like the feature I searching for!

**Comment by Gert-dev** [comment] 2015-11-12 16:11
@pwFoo I've just released version 0.2.0 of all packages. In the base package, you should now find a setting where you can add additional scripts. Let me know if this works for you.

**Comment by pwFoo** [comment] 2015-11-12 19:11
Here is a example stubs.php file. Don't know if that's compatible to your script type?
```
<?php

/**
 * Generated by TemplateStubs module 2013-04-14 11:20:10
 * This file may be overwritten at any time.
 */

namespace tpl;

use Pageimages, Pageimage, PageArray, Page, Password;

/**
 * "admin" template
 *
 * @property string $title Title
 * @property string $process The process that is executed on this page. Since this
 *                           is mostly used by ProcessWire internally, it is
 *                           recommended that you don't change the value of this
 *                           unless adding your own pages in the admin.
 */
class admin extends Page
{}

/**
 * "basic-page" template
 *
 * @property string $title Title
 * @property string $headline Use this instead of the Title if a longer headline is
 *                            needed than what you want to appear in navigation.
 * @property string $summary Summary
 * @property string $body Body Content Yea
 * @property string $sidebar Sidebar
 * @property Pageimages|Pageimage[] $images Images
 */
class basic_page extends Page
{}

/**
 * "permission" template
 *
 * @property string $title Title
 */
class permission extends Page
{}

/**
 * "role" template
 *
 * @property PageArray|Page[] $permissions Permissions
 */
class role extends Page
{}

/**
 * "user" template
 *
 * @property Password $pass Set Password
 * @property string $email E-Mail Address
 * @property PageArray|Page[] $roles User will inherit the permissions assigned to
 *                                   each role. You may assign multiple roles to a
 *                                   user. When accessing a page, the user will
 *                                   only inherit permissions from the roles that
 *                                   are also assigned to the page's template.
 */
class user extends Page
{}
```

The file will be generated inside the project directory.
Is there a way to test the path / script to work as expected?

**Comment by Gert-dev** [comment] 2015-11-12 20:43
Thanks for your test case, I've found a couple of bugs that I fixed and will need to test a bit more (as they might break some things) before I do another release. More in particular they are related to lowercase class names not being added to the suggestions when autocompleting.

Apart from these bugs I'm fixing now, this should indeed work. You can add the path to the `stubs.php` file (relative from your project root) in the package's settings under 'additional scripts to load' and you should be able to receive autocompletion for things such as:

```php
$var = new \tpl\user();
$var-> // Autocompletion for user.
```

Apart from that, note that this feature is mainly for global functions and classes that are available everywhere in your application. For example, suppose your application starts in `index.php`:

```php
// index.php
require 'helper_functions/new_array_walk.php';
require 'helper_functions/some_translate_function.php';

require 'autoload.php';

// ...

$app = new My\Application();
echo $app->run();
```

Here the rest of your code would be written with proper namespacing, classes, etc., but the files included from the folder `helper_functions` will still be available everywhere because they are already incuded here. These two files are the kinds of files this feature was intended for, so they will also show up in autocompletion everywhere.

**Comment by pwFoo** [comment] 2015-11-12 21:51
Autocomplete works with the stubs.php file, but a little bit confusing...
The suggestions from stubs.php are shown after 3 characters. No suggestions on ctrl + tab, but wrong suggestions after one character is written.
But maybe a problem with the autocomplete-plus core plugin in conjunction with your plugin.

I play with some settings, because autocomplete suggestions should be activated by ctrl + space also without typed characters. And improper methods / properties shouldn't suggested, which maybe invoked by the core autocomplete-plus plugin.

Great plugin! Thanks to build such a awesome plugin! :)

**Comment by Gert-dev** [comment] 2015-11-13 15:59
Thanks for your kind words! There were multiple issues at work here I think:
*  Class names with lower case names or namespaces were not being autocompleted properly,
* Atom also has built-in suggestions for the PHP language. Up until now these were always added along with the suggestions from this package. I've added a new option (enabled by default) that disables these, as we already expose all of them ourselves with more information. This should also fix duplicates appearing.

All of these things should be fixed in the 0.2.1 release I've just published.

I've found that the suggestions resulting from the fuzzy matching by autocomplete-plus aren't always that great for me, so I've also enabled the new `Use Alternate Scoring`, which seems to give better results.

**Comment by pwFoo** [comment] 2015-12-12 22:55
Hello @Gert-dev ,

tested your plugin again after some time and can't get it to work...

I tested it with and with and without namespace ("ProcessWire") and also with upper and lower case class names, but no autocomplete suggestions appears for class attributes.

Also to create a class object doesn't work.
```
$var = new \tpl\user();
$var-> // Autocompletion for user.
```

Any idea what I could test?

**Comment by Gert-dev** [comment] 2015-12-30 19:01
The upcoming version (0.4.0) will use a new incremental php-parser-based indexer. This means that there will no longer be any need for your file to be included in the PHP side of the base package nor is Reflection needed anymore. It also means that your stubs file can contain arbitrary code, which will never actually be executed by the indexer. Hopefully this will solve your problem. In any event, debugging the index should be much easier.

**Comment by Gert-dev** [comment] 2016-01-09 10:24
I've just released 0.4.0. Is the new indexer yielding better results for you?

**Comment by pwFoo** [comment] 2016-01-27 19:07
Tried to indexing via Packages -> PHP Integrator build "Indexing failed!".
At the moment I have no time to do more tests, but I will do after some other projects are done...

Thanks for updating and improving that package!

**Comment by Gert-dev** [comment] 2016-01-27 20:41
No problem, take your time. If you keep getting the "Indexing failed" message, you can try following the steps here [1] to see what is causing the error.

[1] https://github.com/Gert-dev/php-integrator-base/issues/41#issuecomment-168337826

**Comment by pwFoo** [comment] 2016-01-30 17:25
After take a quick look I noticed timezone isn't set. So that could be the problem (atom runs inside a docker container, so I'll upgrade the image to test it with changed php.ini.

**Comment by Gert-dev** [comment] 2016-02-07 15:37
Ok, could you let me know if that solved it?

**Comment by Gert-dev** [comment] 2016-03-11 19:49
Assuming that the absence of a response means it's fixed ;-)! Feel free to reopen this if it isn't.

**Closed by Gert-dev** 2016-03-11 19:49 UTC
Labels: question

**Comment by pwFoo** [comment] 2016-03-11 20:39
Hi @Gert-dev 
I'm sorry... haven't tested it yet. Also haven't used atom in the last time because of other projects...
That's why there is no response.

I really like your plugin and the atom editor and will come back soon... 
Thanks!

**Comment by Gert-dev** [comment] 2016-03-12 09:16
No problem! I'm just trying to keep the number of open tickets small to maintain an overview of what's open, but if you do encounter the same problem again (or other problems), opening another ticket is most certainly no problem.

**Comment by pwFoo** [comment] 2016-04-04 14:04
After a short test indexing project looks good to me :+1: 
Thanks for your great packages!

**Comment by Gert-dev** [comment] 2016-04-05 17:17
Great to hear!
